apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service  # Change this to your desired service name
  namespace: default  # Change if needed
spec:
  type: ClusterIP
  selector:
    app: my-app  # Ensure this matches the labels of your pods
  ports:
    - protocol: TCP
      port: 80  # Internal service port
      targetPort: 8080  # The port your application is running on inside the pod
