apiVersion: v1
kind: Service
metadata:
  name: myapp-service # Change this to your desired service name
  labels:
    app: app-label
  namespace: default  # Change if needed
spec:
  type: NodePort
  ports:
    - port: 80 # Internal service port
      targetPort: 80 # The port your application is running on inside the pod
      nodePort: 30008  # Optional; if omitted, Kubernetes will auto-assign a port in the range 30000-32767
  selector:
    app: pod-label # Ensure this matches the labels of your pods